
language: java
sudo: required
dist: trusty
services:
  - docker
cache:
  directories:
    - "$HOME/.gradle"
jdk: oraclejdk8

install:
  - chmod +x ./gradlew
script:
  - ./gradlew buildDockerImage
deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew pushDockerImage